### PR TITLE
Update tar.lua

### PR DESCRIPTION
**Pull request by usstwxy**
fix a bug occured when unrar some .tar files using this module

### CODE REVIEW

**Comment by ignacio** [comment]
What was the bug? I look at the code and I can't see how this change changes the behaviour (although I might still be asleep).

**Comment by hishamhm** [comment]
It does change behavior (the original code breaks the for loop, the new one doesn't).
@usstwxy, do you have an example tar that reproduces the bug? if it's not too big we might include it in the test cases.

**Comment by usstwxy** [comment]
Here is a .tar file which could produce the bug in my machine.
The reason is that sometimes the last character of *octal* in function
*octal_to_number* is not a number.

        octal        #octal
>>> 001751 7
>>> 001751 7
>>> 00001156234 12
>>> 12561100475 12
>>> 015063 6
>>> 000000 7
>>> 000000 7


2015-09-22 0:27 GMT+08:00 Hisham Muhammad <notifications@github.com>:

**Comment by daurnimator** [comment]
the attachment didn't come through.

**Comment by usstwxy** [comment]
It seems that github doesn't allow tar attachment. You can get it by this link https://drive.google.com/file/d/0B0jziWAfhoBOSDYyV08yMGlQRFNBTTdYajBTand2ZDlHYTdJ/view?usp=sharing

**Comment by daurnimator** [comment]
off topic, but while reviewing this I noticed that a header reading failure is reported (`util.printerr(err)`) but not returned (it just ends up throwing on the next line)

**Comment by daurnimator** [comment]
For anyone watching at home, this is the current/old behaviour:
```
$ lua -e 'print(require "luarocks.tools.tar".untar("k.tar", "."))'
chmod: invalid mode: ‘000664 ’
Try 'chmod --help' for more information.
Invalid header magic ±ÁRÑð
lua: /usr/share/lua/5.3/luarocks/tools/tar.lua:105: attempt to index a boolean value (local 'header')
stack traceback:
	/usr/share/lua/5.3/luarocks/tools/tar.lua:105: in function 'luarocks.tools.tar.untar'
	(command line):1: in main chunk
	[C]: in ?
```

While this is the new behaviour (with this PR):
```
$ lua -e 'print(require "tar".untar("k.tar", "."))'
chmod: invalid mode: ‘000664 ’
Try 'chmod --help' for more information.
chmod: invalid mode: ‘000664 ’
Try 'chmod --help' for more information.
chmod: invalid mode: ‘000664 ’
Try 'chmod --help' for more information.
true
```

**Comment by hishamhm** [comment]
> You can get it by this link https://drive.google.com/file/d/0B0jziWAfhoBOSDYyV08yMGlQRFNBTTdYajBTand2ZDlHYTdJ/view?usp=sharing

This fails to download with Firefox (it opens, but the download button in that page redirects to a page that fails)...

**Comment by ignacio** [comment]
Try this link: https://www.dropbox.com/s/o5mocki9urw7bm1/k.tar?dl=0

**Comment by hishamhm** [comment]
@ignacio danke schön! :D

**Comment by mpeterv** [comment]
Is this module (luarocks.tools.tar) actually used anywhere in LuaRocks?

**Comment by hishamhm** [comment]
@mpeterv: not really. It was part of a grand plan that I had back in pre-1.0 days, of replacing all UnxUtils tools in the Windows port with Lua modules (with as little dependencies on binary modules as possible — I was trying to go with "Kepler modules" alone, remember that LuaRocks was born as part of Kepler). UnxUtils was meant to be a stop-gap solution, but it "just worked" and here it is after all these years.

**Pull request merged**
