### PR TITLE
Implement --upgrade and other flags

### PR DESCRIPTION
**Pull request by mpeterv**
This implements flags `--upgrade`, `--lazy`, `--upgrade-deps` and `--reinstall-deps` flags for `install`, `make` and `build` commands on top of modified version of #481.

`install --upgrade rock` does nothing if the latest version of rock is installed. `install --lazy rock` does nothing if any version of rock is installed. `install --upgrade-deps rock` also recursively upgrades dependencies of rock. `install --reinstall-deps rock` also recursively reinstalls them.

This changes output format for dependencies: instead of printing a summary of all missing dependencies before installing all of them, each installation of a dep is announced separately immediately before installation. This allows handling each dependency separately, in a single function (called deps.fulfil_requirement, it's also used to install rock in `luarocks install rock`), without checking status of each one beforehand, which is not cheap for upgrades.

Is it possible to get this, possibly with different interface, in LR2?

TODO:
- Possibly replace `--upgrade-deps` with `--deep-upgrade`, which would imply `--upgrade`.
- Possibly rename `--reinstall-deps` to `--ignore-installed`, like in pip - there it also works for the main rock, not only for deps, because `--lazy` is default.
- Document the new options.
- Add tests.

### CODE REVIEW

**Comment by mpeterv** [comment]
Some examples:

```
luarocks install luafilesystem 1.6.0

Installing https://luarocks.org/luafilesystem-1.6.0-1.src.rock

gcc -O2 -fPIC -I/home/mpeterv/here/include -c src/lfs.c -o src/lfs.o
gcc -shared -o lfs.so -L/home/mpeterv/here/lib src/lfs.o
Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
luafilesystem 1.6.0-1 is now built and installed in /home/mpeterv/here
```

```
luarocks install xavante

Installing https://luarocks.org/xavante-2.3.0-1.src.rock

xavante 2.3.0-1 depends on luasocket >= 2.1 (missing)

Installing https://luarocks.org/luasocket-3.0rc1-2.src.rock

<snip>
gcc -shared -o socket/core.so -L/home/mpeterv/here/lib src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/usocket.o
Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
luasocket 3.0rc1-2 is now built and installed in /home/mpeterv/here (license: MIT)

xavante 2.3.0-1 depends on copas >= 1.2.0 (missing)

Installing https://luarocks.org/copas-2.0.0-2.src.rock

copas 2.0.0-2 depends on coxpcall >= 1.14 (missing)

Installing https://luarocks.org/coxpcall-1.16.0-1.src.rock

Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
coxpcall 1.16.0-1 is now built and installed in /home/mpeterv/here (license: MIT/X11)

Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
copas 2.0.0-2 is now built and installed in /home/mpeterv/here (license: MIT/X11)

Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
xavante 2.3.0-1 is now built and installed in /home/mpeterv/here (license: MIT/X11)
```

```
luarocks install xavante --upgrade

xavante 2.3.0-1 is up-to-date
```

```
luarocks install xavante --lazy

xavante 2.3.0-1 is already installed
```

```
luarocks install xavante --lazy --upgrade-deps

xavante 2.3.0-1 is already installed
xavante 2.3.0-1 depends on luasocket >= 2.1 (up-to-date)
xavante 2.3.0-1 depends on copas >= 1.2.0 (up-to-date)
copas 2.0.0-2 depends on coxpcall >= 1.14 (up-to-date)
xavante 2.3.0-1 depends on luafilesystem >= 1.6.0 (1.6.0-1 installed)

Installing https://luarocks.org/luafilesystem-1.6.3-1.src.rock

gcc -O2 -fPIC -I/home/mpeterv/here/include -c src/lfs.c -o src/lfs.o
gcc -shared -o lfs.so -L/home/mpeterv/here/lib src/lfs.o
Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
luafilesystem 1.6.3-1 is now built and installed in /home/mpeterv/here (license: MIT/X11)

Checking stability of dependencies on the absence of
luafilesystem 1.6.0-1...

Removing luafilesystem 1.6.0-1...
Removal successful.
```

```
luarocks install xavante --reinstall-deps
Installing https://luarocks.org/xavante-2.3.0-1.src.rock

xavante 2.3.0-1 depends on luasocket >= 2.1 (3.0rc1-2 installed)

Installing https://luarocks.org/luasocket-3.0rc1-2.src.rock

<snip>
gcc -shared -o socket/core.so -L/home/mpeterv/here/lib src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/usocket.o
Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
luasocket 3.0rc1-2 is now built and installed in /home/mpeterv/here (license: MIT)

xavante 2.3.0-1 depends on copas >= 1.2.0 (2.0.0-2 installed)

Installing https://luarocks.org/copas-2.0.0-2.src.rock

copas 2.0.0-2 depends on coxpcall >= 1.14 (1.16.0-1 installed)

Installing https://luarocks.org/coxpcall-1.16.0-1.src.rock

Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
coxpcall 1.16.0-1 is now built and installed in /home/mpeterv/here (license: MIT/X11)

Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
copas 2.0.0-2 is now built and installed in /home/mpeterv/here (license: MIT/X11)

xavante 2.3.0-1 depends on luafilesystem >= 1.6.0 (1.6.3-1 installed)

Installing https://luarocks.org/luafilesystem-1.6.3-1.src.rock

gcc -O2 -fPIC -I/home/mpeterv/here/include -c src/lfs.c -o src/lfs.o
gcc -shared -o lfs.so -L/home/mpeterv/here/lib src/lfs.o
Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
luafilesystem 1.6.3-1 is now built and installed in /home/mpeterv/here (license: MIT/X11)

Updating manifest for /home/mpeterv/here/lib/luarocks/rocks
xavante 2.3.0-1 is now built and installed in /home/mpeterv/here (license: MIT/X11)
```

**Comment by hishamhm** [comment]
Whoa, this is major. I'll have to give this a good, close look. But it's definitely something we need.

My initial feedback is that, based on user feedback, I think the expected interface is to have a separate verb, `luarocks upgrade`.

The exercise of writing the user documentation is a good way to gauge if the interfaces are good or too convoluted.

Thank you for this! Yes, I think this can go into LR2.

**Comment by mpeterv** [comment]
> My initial feedback is that, based on user feedback, I think the expected interface is to have a separate verb, luarocks upgrade.

It would make sense for `luarocks upgrade` to work only for rocks that are already installed though. It does have an advantage that some upgrade-specific flags can be added like `--deep`, `--dry-run` (listing outdated deps without installing them), and , of course, `--all` :smile:

**Comment by mpeterv** [comment]
It's rather difficult to figure out the "best" interface for all this, Perhaps the first step should be implementing something simple that can be extended later? I'd prefer to simply add `--upgrade` option that would upgrade both the main rock and its dependencies, recursively, like `pip` does it.

**Comment by mpeterv** [comment]
Needs more work for LR3.

**Pull request closed without merging**
