### PR TITLE
write config directory only if explictly given, use defaults otherwise

### PR DESCRIPTION
**Pull request by Tieske**
implements nr 2 listed [here](https://github.com/keplerproject/luarocks/issues/403#issuecomment-117988369)

### CODE REVIEW

**Comment by hishamhm** [comment]
I'm wondering if LR3 would be a good point to clean up some of the compatibitily stuff such as all those checks for unversioned trees and filenames... I noticed that Unix uses SYSCONFDIR and guesses the filename, while Windows uses SYSCONFIG.

**Comment by Tieske** [comment]
Is something expected or can this be merged? would be nice for the next release

**Comment by ignacio** [comment]
Should we merge this and open an issue to unify Unix and Windows behaviour in LR3 ?

**Comment by hishamhm** [comment]
@ignacio I think it's a good idea. Let's get the improvement out now, and if the behavior changes somewhat, LR3 is a new major release so any future behavior changes are justified.

**Pull request merged**
