### PR TITLE
Show dependency constraints in `luarocks show`

### PR DESCRIPTION
**Pull request by mpeterv**
Currently in "dependencies" section `luarocks show` prints names of all dependencies of the rock, including "deep" dependencies. I suggest that it should only list direct dependencies (using list from rockspec), and that version constraints should be printed, too. E.g. for sailor instead of

```
Depends on:
	lua_cliargs
	xavante
	lua-term
	coxpcall
	busted
	luafilesystem
	rings
	penlight
	datafile
	dkjson
	mediator_lua
	luassert
	lbase64
	wsapi
	wsapi-xavante
	luasocket
	copas
	valua
	say
```

print

```
Depends on:
	lua >= 5.1, < 5.3
	datafile >= 0.1
	luafilesystem >= 1.6.2
	valua >= 0.2.2
	lbase64 >= 2012080
	cgilua >= 5.1.4
	xavante >= 2.3
	wsapi-xavante >= 1.6.1
	busted >= 2.0.rc9
```

### CODE REVIEW

**Comment by mpeterv** [comment]
(turned this issue into PR)

**Comment by mpeterv** [comment]
Any opinions on this?

**Comment by daurnimator** [comment]
I like the sound of this.
Though perhaps there should be a flag to turn on "deep" dependencies?

**Comment by mpeterv** [comment]
@daurnimator do you mean simply reverting to current behaviour when a flag is used or showing deep dependencies alongside direct ones? Because printing constraints for shared deep constraints is not trivial.

**Comment by daurnimator** [comment]
> @daurnimator do you mean simply reverting to current behaviour when a flag is used or showing deep dependencies alongside direct ones? Because printing constraints for shared deep constraints is not trivial.

Lets start with one; then move onto the other? :)

**Comment by hishamhm** [comment]
How about:

```
Depends on:
    lua >= 5.1, < 5.3
    datafile >= 0.1
    luafilesystem >= 1.6.2
    valua >= 0.2.2
    lbase64 >= 2012080
    cgilua >= 5.1.4
    xavante >= 2.3
    wsapi-xavante >= 1.6.1
    busted >= 2.0.rc9
Those are also pulling these packages:
    lua_cliargs
    lua-term
    coxpcall
    rings
    penlight
    dkjson
    mediator_lua
    luassert
    wsapi
    luasocket
    copas
    say
```

**Comment by hishamhm** [comment]
Suggestions on how to rephrase `Those are also pulling these packages:` to avoid dealing with plurals are welcome. :) (Perhaps simply `Indirectly depends on:`, but I avoided this one specifically to avoid the issue of having to print version ranges — `Indirectly pulling:`, maybe?).

Another possible enhancement would be to say stuff such as`cgilua >= 5.1.4 (using 5.2.1-1)`

**Comment by mpeterv** [comment]
@hishamhm great suggestions, implemented!

```
Depends on:
	lua >= 5.1, < 5.3 (using 5.3-1)
	datafile >= 0.1 (using 0.2-1)
	luafilesystem >= 1.6.2 (using 1.6.3-2)
	valua >= 0.2.2 (using 0.3-1)
	lbase64 >= 20120807 (using 20120807-3)
	cgilua >= 5.1.4 (using cvs-5)
	xavante >= 2.3 (using 2.3.0-1)
	wsapi-xavante >= 1.6.1 (using 1.6.1-1)
	busted >= 2.0.rc9 (using scm-0)
	bcrypt >= 2.1 (using 2.1-3)
	remy >= 0.2 (using 0.2.10-1)
	latclient >= 0.4 (using 0.4-1)
	dkjson ~> 2.5 (using 2.5-2)

Indirectly pulling:
	ansicolors (using 1.0.2-3)
	argparse (using 0.5.0-1)
	copas (using cvs-4)
	coxpcall (using cvs-2)
	lua-term (using 0.4-1)
	lua_cliargs (using 3.0-1)
	luasocket (using scm-0)
	luassert (using 1.7.9-0)
	luasystem (using 0.1.0-0)
	mediator_lua (using 1.1.2-0)
	penlight (using scm-1)
	rings (using 1.3.0-1)
	say (using 1.3-1)
	wsapi (using cvs-4)
```

**Comment by hishamhm** [comment]
Awesome! Thank you!!

**Pull request merged**
