### PR TITLE
Set permissions explicitly when copying or moving files.

### LINKED ISSUE #546: Unpacked rocks have creator's permissions
I installed zash's lua-jwc-0.3-1.src.rock: 
```
$ sudo luarocks-5.1 install lua-jwc
Installing https://luarocks.org/lua-jwc-0.3-1.src.rock...
Using https://luarocks.org/lua-jwc-0.3-1.src.rock... switching to 'build' mode
Updating manifest for /usr/lib/luarocks/rocks-5.1
lua-jwc 0.3-1 is now built and installed in /usr (license: MIT/X11)
```

However, it didn't work due to getting installed with odd permissions:
```
$ lua5.1 -ljwc.jwk
lua5.1: module 'jwc.jwk' not found:
	no field package.preload['jwc.jwk']
	no file './jwc/jwk/init.lua'
	no file './jwc/jwk.lua'
	no file './jwc/jwk.lua'
	no file '/usr/share/lua/5.1/jwc/jwk.lua'
	no file '/usr/share/lua/5.1/jwc/jwk/init.lua'
	no file '/usr/lib/lua/5.1/jwc/jwk.lua'
	no file '/usr/lib/lua/5.1/jwc/jwk/init.lua'
	no file '/usr/local/share/lua/5.1/jwc/jwk/init.lua'
	no file '/usr/local/share/lua/5.1/jwc/jwk.lua'
	no file './jwc/jwk.so'
	no file '/usr/lib/lua/5.1/jwc/jwk.so'
	no file '/usr/lib/lua/5.1/loadall.so'
	no file '/usr/local/lib/lua/5.1/jwc/jwk.so'
	no file './jwc.so'
	no file '/usr/lib/lua/5.1/jwc.so'
	no file '/usr/lib/lua/5.1/loadall.so'
	no file '/usr/local/lib/lua/5.1/jwc.so'
stack traceback:
	[C]: ?
	[C]: ?
```
```
$ luarocks-5.1 show lua-jwc

Error: Could not load rockspec file /usr/lib/luarocks/rocks-5.1/lua-jwc/0.3-1/lua-jwc-0.3-1.rockspec (/usr/lib/luarocks/rocks-5.1/lua-jwc/0.3-1/lua-jwc-0.3-1.rockspec: Permission denied)
```
```
$ sudo luarocks-5.1 show lua-jwc

lua-jwc 0.3-1 - JSON Web Crypto

License: 	MIT/X11
Homepage: 	https://code.zash.se/lua-jwc
Installed in: 	/usr

Modules:
	jwc.b64url (/usr/share/lua/5.1/jwc/b64url.lua)
	jwc.jwk (/usr/share/lua/5.1/jwc/jwk.lua)
	jwc.jws (/usr/share/lua/5.1/jwc/jws.lua)

Depends on:
	luaossl
	lua-cjson
	luasocket
```

IIRC, @zash uses a umask of 0077. It appears that this was propagated through the .src.rock, and all the way onto my system.

Luarocks needs to modify the permissions *somewhere* along the line here.

Related: #372

### PR DESCRIPTION
**Pull request by hishamhm**
Should fix #546 and #372. 
Got most of the test suite running locally with `umask 0027` (failed for unrelated reasons).
Can anyone else give this a spin/review? Thanks!

### CODE REVIEW

**Comment by daurnimator** [comment]
One thing I was thinking about was that you may want to respect the umask. i.e. respect the *local* user's umask; *don't* respect the .src.rock creator's umask. @zash thoughts?

**Comment by Zash** [comment]
Respecting the users umask when installing with `--local` would be sensible I think.

**Comment by hishamhm** [comment]
Ah, thanks for the feedback. But I think reading and applying umask would be an additional feature. For now, I'm worried about rocks packaged with incorrect permissions (and whether this PR breaks anything ;) ). Does this look good to go as a first step?

**Comment by daurnimator** [comment]
> Does this look good to go as a first step?

I guess so.

**Pull request merged**
